### ISSUE TITLE
Forgot password... Please Help.

### ISSUE THREAD

**Issue by yang991178** [Liby99/saemanga#1]
As the website does not prompt users to confirm their passwords during sign-up, I may have accidentally entered an undesirable one. Could you please help **reset my password**? (Yes, I'm aware that there's no way to validate my identity since email is not required as part of user creation.)

My username for the web app is yang991178.

**Comment by Liby99** [comment]
It's a shame that I don't have an API that allow me to reset a password without providing the original one. I will try to finish that up tomorrow. As of now, any suggestion on how to improve the user experience on this?

**Comment by yang991178** [comment]
Could you simply reset the password randomly and email it to me for now? My email is yang991178@live.com. Thanks for the promptly response.
